### ISSUE TITLE
Large cooling overcapacity renders reactors nonfunctional

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFutureElectrical#11]
Supplying cooling past ~125% of the required amount results in raising the minimum working throttle setting until that setting exceeds the maximum throttle setting, which makes a reactor that can never produce any output.

A detailed test was run here: http://forum.kerbalspaceprogram.com/index.php?/topic/47786-105-near-future-technologies-merry-christmas-updated-all-to-105/&page=219#comment-2342414

**Comment by ChrisAdderley** [comment]
Complete rebuild of heat generation mechanics is probably required to get this done.

**Comment by ChrisAdderley** [comment]
Appears to be resolved in 0.6.1
