### ISSUE TITLE
Mod disables stock PB-NUK part in 1.8.1

### ISSUE THREAD

**Issue by douglas-moyes** [ChrisAdderley/NearFutureElectrical#117]
Latest release disables stock PB-NUK part. This will break stock craft, or those using stock parts in 1.8.1.

**Comment by ChrisAdderley** [comment]
I am not aware of such an issue. Can you please provide a logfile and a modlist?

**Comment by douglas-moyes** [comment]
Sure... KSP DLC, and:

"REPOSoftTech-Agencies", "version": "V1.5.6.0"
"BonVoyage", "version": "1:1.0.1.1"
"DMagicOrbitalScience", "version": "1.4.3"
"DockingCamKURS", "version": "1.3.7.2"
"ToolbarController", "version": "1:0.1.9.4"
"ClickThroughBlocker", "version": "0.1.9.4"
"DockRotate", "version": "v1.8.1.41"
"FlexibleDocking", "version": "8.0"
"HullcamVDSContinued", "version": "0.2.0"
"KAS", "version": "1.5"
"CommunityCategoryKit", "version": "5.0.0.0"
"KIS", "version": "1.23"
"kOS", "version": "1:1.2.1.0"
"SCANsat", "version": "v18.14"
"TrackingStationEvolved", "version": "5.0"
"ContractsWindowPlus", "version": "9.4"
"ProgressParser", "version": "11.0"
"ContractParser", "version": "9.0"
"EasyVesselSwitch", "version": "2.0"
"ContractConfigurator", "version": "1.28.0"
"CommunityTechTree", "version": "1:3.4.0"
"KerbnetController", "version": "5.0"
"FirespitterCore", "version": "v7.14"
"CommunityResourcePack", "version": "1.3.0.0"
"NearFutureElectrical", "version": "1.1.0"
"B9PartSwitch", "version": "v2.12.1"
"NearFutureElectrical-Core", "version": "1.1.0"
"DynamicBatteryStorage", "version": "2:2.1.1.0"
"NearFutureSolar", "version": "1.1.0"
"NearFutureSolar-Core", "version": "1.1.0"
"GroundConstruction-Core", "version": "2.5.1"
"AT-Utils", "version": "v1.8.3"
"ConfigurableContainers-Core", "version": "2.4.7.1"
"WaypointManager", "version": "2.8.1"
"NearFutureConstruction", "version": "1.2.1"
"AmpYearPowerManager", "version": "1:V1.5.6.0"
"NearFuturePropulsion", "version": "1.2.0"
"NearFutureSpacecraft", "version": "1.3.0"
"NearFutureProps", "version": "1:0.6.1"
"ResearchBodies", "version": "2:V1.11.0.0"
"CommNetConstellation", "version": "1.5"
"ContractConfigurator-CommNetRelays", "version": "v2.1.0"
"SoundingRockets", "version": "1.3.0.0"
"Konstruction", "version": "1.3.0.0"
"MalemuteRover", "version": "1.3.0.0"
"UKS", "version": "1:1.3.0.0"
"USI-Core", "version": "1.3.0.0"
"USI-ART", "version": "1:1.3.0.0"
"USI-EXP", "version": "1.3.0.0"
"USI-FTT", "version": "1.3.0.0"
"USI-LS", "version": "1.3.0.0"
"USITools", "version": "1.3.0.0"
"CapCom", "version": "2.11"
"ScienceAlert", "version": "1.9.8.4"
"GroundConstruction", "version": "2.5.1"
"ConfigurableContainers", "version": "2.4.7.1"
"CommNetAntennasExtension", "version": "2.1.0"
"CommNetAntennasInfo", "version": "2.2.0"
"EvaFollower", "version": "1:1.1.1.4"
"EVAStruts", "version": "6.0"
"EVATransfer", "version": "9.0"
"InfernalRoboticsNext", "version": "v3.0.0"
"InterstellarFuelSwitch", "version": "3.13.0.5"
"InterstellarFuelSwitch-Core", "version": "3.13.0.5"
"ScienceRelay", "version": "6.0"
"KerbalJointReinforcementNext", "version": "v4.1.15"
"PatchManager", "version": "0.0.17.1"
"ScienceSituationInfo", "version": "1:1.3.4"
"RemoteTechRedevAntennas", "version": "0.1.1"
"FirespitterResourcesConfig", "version": "v7.14"
"NearFuturePropulsion-XenonHETs", "version": "1.2.0"

There was another mod StationPartsExpansionRedux that, when installed, removed the nose cones from the construction menus, even though they were still listed in the science parts list as being researched. So yes, it was still part of the game, but the game treated it as being an unavailable part.

**Comment by ChrisAdderley** [comment]
I'm not seeing anything amiss there. The only thing that touches the RTG is the optional RTG patch, but I see you don't have that installed. Same with this nosecone issue, SSPX is also my mod and that doesn't have anything that touches nosecones.

I have tested this by loading up an install with NFE and SSPX ( with dependencies) and these issues do not occur on my end.

I'm very tempted to say that it's another mod. However to actually diagnose the problem I still need a logfile.
