### ISSUE TITLE
3.75m battery did not make it through "energy storage rework"

### ISSUE THREAD

**Issue by doktorjet** [ChrisAdderley/NearFutureElectrical#120]
It's stuck in 
https://github.com/ChrisAdderley/NearFutureElectrical/tree/5361fd2ee45a42db57bc094bbcdd851db0a0a2a2/GameData/NearFutureElectrical/Parts/Batteries/battery-375
and not available in master branch.

**Comment by ChrisAdderley** [comment]
Well... Yeah: https://github.com/ChrisAdderley/NearFutureElectrical/blob/708ab6e849a9f7a311b68c0792bdbec273ff3f81/changelog.txt#L72

**Comment by doktorjet** [comment]
And what about those who do not want Restock+? It does not suit well along SXT Continued, I suppose...
3.75m battery has much more sense in NearFutureElectrical pack to couple with 3.75m reactors or in StationPartsExpansionRedux pack to couple with 3.75m station parts than in separate stock-enchancing mod like Restock+.

**Comment by doktorjet** [comment]
BTW... You are one of Restock+ authors, aren't you? Maybe you concider adding some SXT parts to it like it was with Ven's Rewamp? I mean airplane parts specifically. Than Restock+ will efficiently replace most good things SXT had to offer.

**Comment by ChrisAdderley** [comment]
> 3.75m battery has much more sense in NearFutureElectrical pack to couple with 3.75m reactors or in StationPartsExpansionRedux pack to couple with 3.75m station parts than in separate stock-enchancing mod like Restock+.

I'd view this differently. The 3.75m battery is a critical missing part for 3.75m construction, and it should not be packed in with a mod specifically for nuclear reactors. It should instead be packed with a mod that solves the problem of missing 3.75m (and 1.875m) parts, which in my catalog is Restock+.

> BTW... You are one of Restock+ authors, aren't you? Maybe you concider adding some SXT parts to it like it was with Ven's Rewamp? I mean airplane parts specifically. Then Restock+ will efficiently replace most good things SXT had to offer and there will be no trouble with choice. ;)

A good place to start there is this issue: https://github.com/PorktoberRevolution/ReStocked/issues/17. I regularly look through this when there are comments, see if they fit, and scope them for inclusion in a future version.

**Comment by doktorjet** [comment]
Ok. Restock+ appeared to have neglible issues with SXT (just doubled some parts), so case can be closed.
