### ISSUE TITLE
"No part selected exiting transfer mode"

### ISSUE THREAD

**Issue by barfingskull** [ChrisAdderley/NearFutureElectrical#16]
When attempting to move nuclear fuel and waste between two docked vessels, the above "No part selected exiting transfer mode" error occurs.  This has been mentioned in the KSP forum thread.  There's an available engineer, but no transfer is possible in this state.

Thanks!
-BS

**Comment by ChrisAdderley** [comment]
As a note to future Chris, evidently your connectivity checker doesn't understand docked ships. Revise this!.

**Comment by ChrisAdderley** [comment]
This is fixed, I believe, in 0.7.0.

**Comment by ChrisAdderley** [comment]
Not fixed.

**Comment by ChrisAdderley** [comment]
Exhaustive testing seems to indicate that this is fixed in the upcoming 0.7.5
