### ISSUE TITLE
Decaying core life when idle

### ISSUE THREAD

**Issue by SkyKaptn** [ChrisAdderley/NearFutureElectrical#18]
The core life of reactors decreases when they are idle (deactivated). This happens regardless if they are untouched, or have been started and then deactivated. **Note**: I have just tested with the Garnet reactor.

Steps to reproduce issue:
-Place a vessel on the launchpad with a reactor.
-Do not activate the reactor.
-Time warp a couple of years ahead.
-Watch the core life rapidly count down to 0 **after** time warp

**Comment by ChrisAdderley** [comment]
Looks like some kind of horrific timewarp catchup mechanic is playing havoc with things.

**Comment by SkyKaptn** [comment]
I also see that the included CommunityResourcePack for NFE 0.7.1 is outdated, but I do not think this can be the cause for the resource's wierd decay. The scripts look the same.

**Comment by ChrisAdderley** [comment]
Changes are that's unrelated.

**Comment by ChrisAdderley** [comment]
I can't repro this actually. Steps taken:

1. Build ship (2 parts, 2.5m command pod + Garnet reactor)
2. Launch
3. Timewarp many days (~300)
4. Turn off timewarp, nothing seems to happen

Can I request a modlist, some screenshots, any more info?

**Comment by SkyKaptn** [comment]
> You actually shouldn't be able to see the Core Life while the reactor is off at all even. 
 -There was a step in repro that I didn't mention: Activate the reactor the reactor after time warp.

Anyways, the fact that you could not repro made me think... I have two installs of KSP. One "standard, heavily modded" which is doing fine with core life, and one with RSS. The RSS mod being the only difference beween them. I just found out that it is the RSS install that screws up core life. _I am only able to repro the bug in the RSS install._ Probably something to do with the different way to keep track of time (1 day = 24hrs in RSS. Versus 1 day = 6 hrs in regular KSP). There are also different time warp factors there, much higher ones.

But still wierd and unfortunate. With the 10x travel distances in RSS, the need for ions etc is truly essential.

**Comment by SkyKaptn** [comment]
I managed to pin-point the issue. It only happens at max time warp in RSS which is somewhat higher than stock. (rate7 = 6000000) For the time being I will just edit the warp factors in RealSolarSystem.cfg to something non-destructive. Original script below:



`REALSOLARSYSTEM
{
	// GENERAL PARAMETERS
	//cam01NearClip = 1
	
	timeWarpRates
	{
		rate1 = 10
		rate2 = 100
		rate3 = 1000
		rate4 = 10000
		rate5 = 100000
		rate6 = 1000000
		rate7 = 6000000
	}
}
@REALSOLARSYSTEM:FOR[RSSConfig]
{
	RSSConfig = True
}`

**Comment by ChrisAdderley** [comment]
Huh well I'm going to mark this as not a bug for now - I can't see what I could do to fix this. Not sure why an increased warp rate would cause the problem.
