### ISSUE TITLE
Add TweakScale support for fission reactors

### ISSUE THREAD

**Issue by artyom-y-razinov** [ChrisAdderley/NearFutureElectrical#20]
Problem: fission reactors are scaleable, but they produce constant EC/s.
Workaround: for increasing EC production user can add more reactors, but more parts will affect performance of the game (down to 2 fps with phisics time warp on my computer for 200 parts vessel).

I started to make TWEAKSCALEEXPONENTS, but faced with lots of settings of ModuleCoreHeat. So, please, add support for it, because you understand how those magic numbers work.

**Comment by ChrisAdderley** [comment]
I don't want to support TweakScale, it adds a large host of issues that also offend my artistic sensibilities. I did it for Mk4 and got tons of support headaches.
