### ISSUE TITLE
Capacitors not recharging when ship is not loaded

### ISSUE THREAD

**Issue by WildLynxDev** [ChrisAdderley/NearFutureElectrical#21]
Looks like capacitors not recharging when switched to other ship, which is not in this physics range, and time warped.
They are recharging only is ship is current ship.

**Comment by ChrisAdderley** [comment]
Not really a bug, same thing'll happen for most electricity producing things. Implementing this doesn't have much payoff.

**Comment by ChrisAdderley** [comment]
Targeted for future patch

**Comment by ChrisAdderley** [comment]
Resolved in 0.8.3
