### ISSUE TITLE
UI improvement.

### ISSUE THREAD

**Issue by WildLynxDev** [ChrisAdderley/NearFutureElectrical#22]
I propose small UI improvement for NFT(E)

1. Capacitor control panel can be activated by action key.
2. Capacitor control panel can be activated from Blizzy or stock control panel. Icon is capacitor symbol.
3. Reactor control panel is created and be activated from Blizzy or stock control panel. Icon is atom symbol.
Reactor control panel should be designed just same as popup window for reactors, except few extra buttons to switch to next/previous reactor, name of reactor (renamable ?) and close button.

**Comment by ChrisAdderley** [comment]
1. action group assignment or hotkey?
2. Seems reasonable, though I probably won't go through the effort of doing it for blizzy's toolbar
3. Probably not going to happen, don't see the need.

**Comment by WildLynxDev** [comment]
1. Enable this option as Action group. As I understand, it's easier for you, and hotkeys are already crowded.
2. 3. Both reactors and capacitor have ship-wide effects. But looking for them in the big ship's structure is a bit of a hassle. Reactors are big in most cases, and finding them is easier task then small capacitor tucked into some service bay. The need for separate control panel arises from general KSP (especially heat system) buggeness, so you can keep watch on them, and popup menus have a bad habit of hiding behind other windows. 
Toolbars are crowded too... may be, it's best to cut it even further - no toolbar integration whatever - panels only accessible via rmb menu button and action group.

-- Anyway, it's UI improvement request, and thus must have low priority.

**Comment by ChrisAdderley** [comment]
I am convinced, and will put it on the roadmap. Going to split this into other issues.
