### ISSUE TITLE
MX-5 'Hermes' Fission Reactor

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/NearFutureElectrical#34]
Final reactor model, 3.75m, ~2.5x height of F.L.A.T. 5-6 MW electrical output. 

- [x] Model
- [x] Unwrap
- [x] Textures
- [x] config

**Comment by lOmicronl** [comment]
Suggested stats:

5000 Ec/s variant: mass 10.0, cost 1003600, heating 3150, fuel carried 640

6000 Ec/s variant: mass 12.0, cost 1206050, heating 3750, fuel carried 770
