### ISSUE TITLE
CAP-101 is in the wrong tech tree node

### ISSUE THREAD

**Issue by koloshich** [ChrisAdderley/NearFutureElectrical#39]
The small radial CAP-101 was always the first to be researched. But now it's in the scienceTech node, costing 300 science. Meanwhile, the larger radial CAP-106 is in advancedElectrics for 160 science, and the inline CAR-1.6K is in Electrics for 90 science.

Intended change?

**Comment by ChrisAdderley** [comment]
This has literally never been changed - my only theory is that this problem must have surfaced in KSP 1.0. You're just the first person to nice it. Should be resolved in the next version (d9b6f58772ee81369d42f7abce54ac2572aa4a76)
