### ISSUE TITLE
Capacitor discharge rate is much too slow

### ISSUE THREAD

**Issue by lOmicronl** [ChrisAdderley/NearFutureElectrical#43]
Using NF Electrical 0.8.2 on KSP 1.2.2, with everything it brings bundled, and nothing else.

Capacitors somehow discharge at 1/100th the intended rate. For example, the 1.25m inline capacitor with 8000 charge only discharges at between 8 and 16 Ec/s depending on the slider.

Unsure if this bug is 1.2.2 related or if it existed on other 1.2.x versions, I haven't used capacitors since 1.1.3.

**Comment by ChrisAdderley** [comment]
Resolved in next version.

**Comment by ChrisAdderley** [comment]
Seems to have resurfaced, but only in the capacitor window. Will look at this when redoing said window.

**Comment by ChrisAdderley** [comment]
Should be resolved, now in testing.
