### ISSUE TITLE
Radiator panels explode after a few minutes

### ISSUE THREAD

**Issue by tfischer4765** [ChrisAdderley/NearFutureElectrical#5]
I've seen this issue a few times now: the radiator panels from NearFuture tend to explode after a few minutes without apparent reason, i.e. without showing an overheat bar or any sort of collision. It seemed to me (unconfirmed, WAY too small a data sample) that panels attached to a reactor tuned to a higher output tended to explode quicker than such attached to a reactor with lower output.

**Comment by ChrisAdderley** [comment]
There are no radiators in this pack anymore. If you have any, you're running an old version and they are not compatible with KSP 1.03+.

**Comment by tfischer4765** [comment]
I have now verified this with the Heat Management radiators as well. What apparently happens is this: When the reactor spools up, while the reactor itself stays at 350K, the radiators get very hot very quickly. Around 1800 K, they just explode without ever showing an overheat bar. In the temp debug overlay they already show as whiteish-yellow at the time, so either there's some sort of misconfiguration in your cfgs, or maybe you're running into some hard-coded thermal cap of KSP?

**Comment by tfischer4765** [comment]
When I checked the debug output, I noticed the reactors don't actually generate any heat, the heat is actually generated in the attached radiator panels. Also I noticed that the "Current thermal radiation" figures in the context menu is not in sync the figures for required power dissipation given in the part description. E.g. the M-Exp is supposed to generate some 200kW of heat, but the panels together say they are dissipating only 14kW. (I hooked two XR-6000 to a M-EXP to see what would happen)

The thermal debug figures for the M-Exp have Int Flux aka generated heat at zero. The XR-6000 show an int flux of 100 each, but only -11 or so cond and conv flux combined. No wonder they are overheating. I'm going to watch this little experiment for another hour or so and see if the system reaches an equilibrium with these insanely overpowered radiators and if so, post the figures here.

**Comment by tfischer4765** [comment]
I think I see what's going on now. I ran the same test again with an M-EXP, this time with two Tau radiators attached and hyperedited to orbit (because for some reason the game won't let me cheat-disable convection)  At a temperature of 1000 the rad flux was a mere -8, so you can imagine it won't get to the necessary -100 by the time the radiator reaches its destruction temperature. I'm sorry I don't have the exact figures, but my machine threw a kernel oops at me.

I think what you're doing is this (correct me if I'm wrong): You divide the "heat generated" figure from the reactor among all radiator panels that are attached to it and throw it at them as int flux. Long story short, I guess my initial gut feeling was right. Your thermal calculations are off about five- to tenfold regarding the heat dissipation capability of the radiator panels. On an unrelated note, I'd suggest ditching any fancy int flux magic you may have and using the stock conduction flux mechanism, it'll be much easier to integrate with third-party mods.

**Comment by ChrisAdderley** [comment]
Yeah, you're pretty wrong ;).

I'm going to point you to multiple indications (the thread title, the kerbalstuff page, the curseforge page) that indicates that HC is for KSP 1.02. Squad changed key components of how the thermal sim worked in 1.03 and that pack has not yet been updated for it! The reactors work with the stock radiators as noted in their description fields.

And for the record "fancy int magic" is how the stock radiators work as well.

**Comment by tfischer4765** [comment]
You know, in hindsight I _could_ have checked the changelog first to see if there were any changes in the thermal system from .2 to .4. All that good testing effort wasted. I'll go check out  the "stock fancy int flux magic" now. That I'll have to see for myself, because I'm pretty sure last time I checked they used cond flux. Then again, I don't know if that was .2, .3 or .4

**Comment by tfischer4765** [comment]
Ok, I've tried this again, with a freshly downloaded NFE and a fresh install of KSP just to be sure. I see neither stock int flux magic nor working stock radiator panels here, what am I missing?
![screenshot0](https://cloud.githubusercontent.com/assets/1536481/8766280/725c236c-2e32-11e5-9e34-24f63174f650.png)
![screenshot1](https://cloud.githubusercontent.com/assets/1536481/8766283/7a64d14e-2e32-11e5-91be-5db78d3ca4e5.png)

**Comment by lOmicronl** [comment]
Radiator panels did not work in 1.0.4 because they did not have an active component. They only passively radiated heat that naturally conducted into them. However, reactors are insulated, and do not conduct heat to other parts. Active cooling is required.

In 1.0.5, radiator panels gained active cooling abilities similar to (but slightly more area limited than) the folding radiators. They will be able to cool reactors in the future. However, NF Electrical still needs to be updated to 1.0.5 first before this works.

(This old issue feels ripe for closing now.)
