### ISSUE TITLE
Timewarp Power Control Request

### ISSUE THREAD

**Issue by Exavier724** [ChrisAdderley/NearFutureElectrical#52]
Would it be possible to get an option we can set on a reactor to automatically change its power level (or enable/disable it completely) when time warp is engaged? I've lost count of how many times I have burned out the fuel in the Kerbal Atomics Engines (As well as the smaller EXP reactor & the USI patched reactors in bases) where I have accidentally left the things at full power while time warping between maneuver nodes or arbitrary time points (for bases).

**Comment by ChrisAdderley** [comment]
In testing, slated for 0.8.7
