### ISSUE TITLE
Capacitors don't play well with kOS

### ISSUE THREAD

**Issue by magnevan** [ChrisAdderley/NearFutureElectrical#59]
You used to be able to set a "percent power" field on capacitors via kOS with a range from 50-100. However, now the only field available to set is discharge rate. However, this field will also only accept values from 50-100.

This means that:
1. You can cheat with kOS by setting a much lower discharge rate on capacitors than intended (even the largest ones will allow you to set it to 50)
2. You can't manage your capacitors very effectively since this discharge rate is so low.

I used to use this script http://pastebin.com/EYViWNX9 to manage my capacitors previously.

**Comment by ChrisAdderley** [comment]
I know nothing about kOS, but why can't you set adjustedDischargeRate? This is the actual "real" discharge rate that instead of setting a percent slider that affects it, which should now canonically be set directly. It is unconstrained except by the UI, so I guess I can ensure that it is clamped in the future to avoid setting low rates...

**Comment by ChrisAdderley** [comment]
Would ask you to let me know whether the changes in the latest version of NFE have worked for this.

**Comment by magnevan** [comment]
Yes, I will take a look at it soon and try to provide some more details. Basically last I looked the only field available for setting was "discharge rate".

**Comment by ChrisAdderley** [comment]
Thanks. If DischargeActual is not available for setting, you might want to see how kOS decides that an field is available for setting. In the current implementation:

        // The maximum discharge rate
        [KSPField(isPersistant = false)]
        public float DischargeRate = 10f;

        // The scalar to apply to the maximum discharge rate to determine the minimum rate
        [KSPField(isPersistant = false)]
        public float DischargeRateMinimumScalar = 0.5f;

        // The UI control responsible for setting the discharge rate, min/max are adjusted in code to match the numbers above
        [KSPField(isPersistant = true, guiActive = true, guiActiveEditor = true, guiName = "Discharge Rate"), UI_FloatRange(minValue = 50f, maxValue = 100f , stepIncrement = 0.1f)]
        public float dischargeActual = 100f;

**Comment by ChrisAdderley** [comment]
Marking this resolved... reopen if you have issues.
