### ISSUE TITLE
RTG Decay for Atomic Age

### ISSUE THREAD

**Issue by Stratickus** [ChrisAdderley/NearFutureElectrical#64]
I tried adding a PR, but sadly, I couldn't quite figure it out. In any event, here is a MM patch for Atomic Age's KANDL RTG engine if you're interested.

	@PART[nuclearEngineKANDL]:NEEDS[NearFutureElectrical]:AFTER[AtomicAge]
	{
		!RESOURCE[ElectricCharge]{}
		!MODULE[ModuleGenerator] {}
		!MODULE[ModuleAlternator]{}
		MODULE
		{
			name = ModuleRadioisotopeGenerator
			BasePower = 0.75
			HalfLife = 8.35
			EasyMode = true
		}
	}

Cheers,

**Comment by ChrisAdderley** [comment]
Added and targeted for next version.
