### ISSUE TITLE
MRS Quad-Nuclear Engine doesn't utilize reactor mechanic

### ISSUE THREAD

**Issue by Ununtri** [ChrisAdderley/NearFutureElectrical#67]
While the stock LV-N engine uses reactor, and because of that has variable Isp and thrust depending on the thermal output, it's MRS enlarged version "Quad" doesn't. The patch Config from KSP forum makes so that engine has a built-in reactor, however it doesn't use it properly - the power output and thrust are not dependent and it can run with the reactor shut down.

**Comment by ChrisAdderley** [comment]
What patch is this? Currently only KA and the LV-N are supported by the reactor patch because of its experimentalness. Everything else is super unsupported.

**Comment by Ununtri** [comment]
The patch was created by autumnalequinox on June 21, it's available on Kerbal Atomics thread on page 10.

**Comment by ChrisAdderley** [comment]
If it's not in the download, it's not official, so you should talk to him about any issues with it.

**Comment by Ununtri** [comment]
I'm gonna try to reach out to him, however it may have happened that due to numerous updates since June making a patch for it is not that simple now. The main reason I asked question there is because of a chance to get a quick and straight answer.
Anyway, the support for a single engine in this mod would be appreciated, but I know it's your work and you have your priorities. As always thanks for working on it despite it being completely voluntary.

**Comment by ChrisAdderley** [comment]
Thanks for the comments :)

This patch is still highly experimental and I only support a few engines because of the experimental nature and the rapidly fluctuating config base. Once the patch is completely stable I will expand support.

**Comment by ChrisAdderley** [comment]
If you are using this patch, I would really appreciate contributions to the discussion about it here http://forum.kerbalspaceprogram.com/index.php?/topic/130503-122-kerbal-atomics-fancy-nuclear-engines-march-2-various-fixes/&do=findComment&comment=3017887 so I can codefix and stabilize it.
