### ISSUE TITLE
Nuclear reactors always report 100% load

### ISSUE THREAD

**Issue by pyalot** [ChrisAdderley/NearFutureElectrical#8]
No matter the actual load, they always show 100%. Umbra Space industries reactors don't do that.

**Comment by ChrisAdderley** [comment]
This isn't really a bug, these reactors are different than the USI ones. However I will see if I can hide that field.

**Comment by ChrisAdderley** [comment]
Hidden in https://github.com/ChrisAdderley/NearFutureElectrical/commit/3b537b28aaede9cb2782418c8d508c463a1c8274 , will be in 0.6.1

**Comment by pyalot** [comment]
That's fine, I just found it strange that a field was shown that seemed to have no meaning.
