### ISSUE TITLE
B-800 cost is inconsistent with other parts

### ISSUE THREAD

**Issue by tsmelt** [ChrisAdderley/NearFutureElectrical#80]
The cost of the B-800 (battery-rad-125) seems very low.  It looks like a typo was introduced in a75176fa1486018c73b8f870f13072269e6f3709.

**Comment by ChrisAdderley** [comment]
Oh no, the secret free battery was discovered!

**Comment by ChrisAdderley** [comment]
Resolved in bbfcd6a, will be in next patch.

**Comment by tsmelt** [comment]
You're my hero :)

**Comment by ChrisAdderley** [comment]
Resolved in latest release
