### ISSUE TITLE
Automated mode for reactors

### ISSUE THREAD

**Issue by blackliner** [ChrisAdderley/NearFutureElectrical#84]
Hi, i am almost done with the automated mode. Is there a way i can distribute the package to interested users for testing purpose? Or do you want to take a look at it first?

Here is my fork: https://github.com/blackliner/NearFutureElectrical
The gamedata folder should work as it is. The new field `AutomatedMode` is true by default, but eventually thats the users choice, and it would ofc be disabled in a release. The "controller" tries to achieve the target EC level, i defaulted it to 90%.

cheers!

**Comment by ChrisAdderley** [comment]
I'd distribute it to interested parties via PM. This needs to be 
1. Rebased against the latest version
2. Tested against all the heat system cases 
At the very least.

**Comment by blackliner** [comment]
1. Do I have to "rebase" it manually, or are there tools within GitHub that might be handy?
2. Do you have some tests specified?

(2.1) it happened a few times that the reactor exploded after warp, but that was mentioned in the forum already and you meant "OMFG stock heat sucks" :-) it might have to do with your single entry in the coreheatmodule, maybe set a "safety" entry with 0 heat gen during warp

**Comment by ChrisAdderley** [comment]
1. You could try a merge from my `dev` to yours. I would do it in command line with `git rebase` though. Specifically you need the last fixes for that timewarp heat issue from the last release.
2. Yes.
a. Test timewarp heat behaviour (up to max, down from max repeatedly) when started.
b. Test timewarp heat behaviour (up to max, down from max repeatedly) when shutdown
c. Test load/save heat behaviour (after reactor left running or reactor left cold)
d. Test load/save heat behaviour with large load time delta (after reactor left running or reactor left cold)
e. Test all thermal behaviour with lower than expected number of radiators
f. Test all thermal behaviour with larger than expected number of radiators
g. Test thermal behaviour with multiple reactors (multiple same size, multiple different size)
h. Test integration with KA (hard to quantify)

**Comment by ChrisAdderley** [comment]
Kinda stale. Closing.
