### ISSUE TITLE
Not seeing RTG decay

### ISSUE THREAD

**Issue by KSAMissionCtrl** [ChrisAdderley/NearFutureElectrical#95]
[output_log.txt](https://github.com/ChrisAdderley/NearFutureElectrical/files/1617473/output_log.txt)

I have just NFE and its dependencies installed to test, have placed the patch file in the Patches folder (suitably, I know it can go anywhere) and set all the `EasyMode` parameters to `false`. I built a simple probe core, battery and the NFE RTG and sat it out on the pad, timewarped for a year and PAW still showed 100% efficiency and using Hyperedit to drain the batteries I saw them recharge at 2.98EC/s (3.0 minus the probe core usage). Pushed the time up 8 years with Hyperedit and still no change to power output. What did I miss?

On a related note, does NFE scale the half-life with chosen game time format? So I have it set to Earth time does that mean an 8yr half life lasts 8 Earth years or still only 8 Kerbin years?

**Comment by ChrisAdderley** [comment]
It's kinda a toss-up with KSP as to whether something will count as enabled or not on the pad. Recommend putting it in orbit or staging it to 100% force an enabled state.

**Comment by KSAMissionCtrl** [comment]
good call, there's no staging on this simple craft so I threw it up into orbit and the decay began right away. Then when I reloaded the launchpad a physics bounce caused the state to change from prelaunch and decay worked on the pad too. This all makes sense when I look at the code and see you're basing it on mission time - so it's not that anything is enabled/disabled it's just with the MET remaining at 0 the RTG is stuck at full efficiency. Given that RTGs decay from the moment they are built and not when detached from some external power source at launch time I expected it to work without having a mission started, but game-wise it makes sense as and is also an easy way to keep track of time passed. I knew it had to be a misunderstanding rather than a bug
